version: "3.3"
services:
  captcha-solver:
    build:
      context: containers/api_container
    container_name: captcha-solver
    ports:
      - 2103:2103
    command: python3.7 app.py
    environment:
      - PORT=2103
    volumes:
      - ./utils:/utils/
      - ./model:/model/
      
  captcha-trainer:
    build:
      context: containers/train_container
    container_name: captcha-trainer
    command: python3.7 train.py data/captcha_train -s model/
    volumes:
      - ./data:/data/
      - ./utils:/utils/
      - ./model:/model/
